# Generated by Django 4.2.10 on 2025-05-25 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Subtitle"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/images/%Y/%m/%d/",
                        verbose_name="Image",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publication Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("poder", "Power"),
                            ("tributos", "Tax"),
                            ("saude", "Health"),
                            ("energia", "Energy"),
                            ("trabalhista", "Labor"),
                        ],
                        default="poder",
                        max_length=15,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_pro_content",
                    models.BooleanField(
                        default=False,
                        help_text="Check this option if content is exclusive for PRO clients.",
                        verbose_name="PRO Content",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
                "ordering": ["-publication_date", "-created_at"],
            },
        ),
    ]
