# Generated by Django 4.2.10 on 2025-05-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan Name")),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("info", "JOTA Info"), ("pro", "JOTA PRO")],
                        default="info",
                        max_length=10,
                        verbose_name="Plan Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price in BRL",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "has_trial",
                    models.BooleanField(default=False, verbose_name="Has Trial Period"),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of trial days for this plan",
                        verbose_name="Trial Period Days",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Promotional discount percentage",
                        max_digits=5,
                        verbose_name="Discount Percentage",
                    ),
                ),
                (
                    "discount_valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Discount Valid Until"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
            },
        ),
        migrations.CreateModel(
            name="Vertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("poder", "Power"),
                            ("tributos", "Tax"),
                            ("saude", "Health"),
                            ("energia", "Energy"),
                            ("trabalhista", "Labor"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Vertical",
                "verbose_name_plural": "Verticals",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the subscription should automatically renew",
                        verbose_name="Auto Renew",
                    ),
                ),
                (
                    "renewal_reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="Renewal Reminder Sent"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="plans.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
